version: '3.3'

services:
  nginx:
    container_name: nginx
    depends_on:
      - php
    image: nginx:1.19
    links:
      - php
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./application:/usr/share/nginx/html/library
      - ./docker/nginx/config/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/ssl/
    working_dir: /usr/share/nginx/html/library

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    expose:
      - 9000
    networks:
      - app-network
    restart: always
    volumes:
      - ./application:/usr/share/nginx/html/library
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /usr/share/nginx/html/library

  mysql:
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'app'
    image: library/mysql:5.7.33
    networks:
      - app-network
    restart: always
    volumes:
      - ./docker/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/db:/var/lib/mysql:rw
    working_dir: /var/lib/mysql

networks:
  app-network:
    driver: bridge